# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4366ac6c6b2691860b852304c84463ab765128787ee4eab6f7b90b8b6960b4b25ec693a3c5cf6db2a5f13648cdb60bd90ca20d0269c3395c45972d51d9333f16

test:
  secret_key_base: aee67e5f3c176041e7ade2cd970ff7160cd7691fb197745bbf42926926f14d63df437a101849f3de8835faaa333352ab3c3d30518fca2819b813a724f5131074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
